# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_uIQErzhgUesuaafxRShgiECIDgaCxX
"""

scores = list(map(int, input().split()))

count = 0

for score in scores:
    if score < 60:
        count += 1

print(count)