# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKnsnz-SbEHBdTm4Kr9I1vp6VrC7dLaA
"""

scores = input().split()
count_fail = 0

for i in scores:
  if int(i) < 60:
    count_fail += 1

print(count_fail)


sum = 0
count = 0

for i in scores:
  sum += int(i)
  count += 1

if count > 0:
  average = sum / count

max_score = max(scores)
min_score = min(scores)

print("不及格數量:", count_fail)
print("最大值:", max_score)
print("最小值:", min_score)
print("平均值:", average)
