# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_uIQErzhgUesuaafxRShgiECIDgaCxX
"""

scores = list(map(int, input().split()))

count = 0

for score in scores:
    if score < 60:
        count += 1

max_score = max(scores)
min_score = min(scores)

print("不及格數量:", count)
print("最大值:", max_score)
print("最小值:", min_score)